# fly.toml app configuration file for a multi-process Docker deployment
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'bitwave' # Change this if you chose a different name on the website
primary_region = 'bom' # Change this if you selected a different region

[build]
  dockerfile = "Dockerfile"

# This defines the web server process that the public connects to
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# This defines the background worker process
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["worker"]

# This creates the persistent storage disk
[mounts]
  source="bitwave_storage"
  destination="/app/storage"

# This tells Fly how to run each process
[processes]
  app = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:8080 app:app"
  worker = "python worker.py"
