services:
  # A Web Service for our Flask App
  - type: web
    name: bitwave
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # Use a threaded worker for stability with background tasks and a long timeout
    startCommand: "gunicorn --workers 1 --threads 10 --timeout 120 app:socketio"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    # A Persistent Disk to store our downloads
    disks:
      - name: storage
        mountPath: /opt/render/project/src/storage
        sizeGB: 1
