services:
  # A Web Service for our Flask App
  - type: web
    name: bitwave
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    # Use a threaded worker, which is more stable for this app architecture
    startCommand: "gunicorn --workers 1 --threads 10 --timeout 120 wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    # A single persistent disk for all storage
    disks:
      - name: storage
        mountPath: /var/data
        sizeGB: 1
